name: "Build and deploy"
run-name: "Build and deploy branch ${{ github.ref_name }} to environment ${{ inputs.environment || 'qa' }} by @${{ github.actor }}"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - none
          - dev
          - test
          - qa
        default: test
        description: Deploy to environment?

permissions:
  packages: write

jobs:
  build:
    name: 'Build'
    uses: hwolf/workflows/.github/workflows/build.yml@main
    with:
      runner: ubuntu-latest
    secrets: inherit

  terraform:
    name: 'Terraform'
    uses: hwolf/workflows/.github/workflows/verify-terraform.yml@main
    with:
      runner: ubuntu-latest

  publish:
    name: 'Publish image'
    if: inputs.environment != 'none'
    needs:
      - build
      - terraform
    uses: hwolf/workflows/.github/workflows/publish-image.yml@main
    with:
      imageName: ${{ vars.IMAGE_NAME }}
      runner: ubuntu-latest

  deploy:
    name: 'Deploy'
    if: inputs.environment != 'none'
    needs:
      - publish
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      imageName: ${{ vars.IMAGE_NAME }}
      environment: "${{ inputs.environment || 'qa' }}"
      runner: ubuntu-latest
    secrets: inherit
