name: "Deploy to PRD"
run-name: "Deploy to prd by @${{ github.actor }}"

on:
  deployment:

permissions: write-all

jobs:
  deploy-prod:
    name: "Deploy to PRD"
    if: github.event.deployment.environment == 'qa'
    uses: hwolf/workflows/.github/workflows/deploy.yml@main
    with:
      environment: "prd"
