name: "Test"
run-name: "Test ${{ inputs.environment }} -> ${{ inputs.environment && inputs.environment != 'none' && inputs.environment || 'qa' }}"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          pack --version
